stages:
  - build
  - test
  - deploy

build_image:
  stage: build
  script:
    - docker build -t myrailsproject .

test:
  stage: test
  script:
    - docker run myrailsproject bundle exec rspec

deploy:
  stage: deploy
  script:
    - export AWS_REGION=us-west-2
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY
    - eval $(aws ecr get-login --no-include-email --region $AWS_REGION)
    - docker tag myrailsproject:latest $ECR_REPOSITORY_URI:latest
    - docker push $ECR_REPOSITORY_URI:latest
    - aws ecs update-service --cluster [cluster name] --service [service name] --task-definition [task definition name]:[task definition revision] --region $AWS_REGION
